runmode: debug                 # 开发模式, debug, release, test
addr: :9090                  # HTTP绑定端口
name: apiserver              # API Server的名字
url: http://127.0.0.1:9090   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数
db:  # DB 配置 部署时环境变量覆盖
  name: treehole
  addr: 127.0.0.1:3306
  username: root
  password: 258789hxr
redis:  # redis 配置
  network: tcp
  addr: 127.0.0.1:6379
account:  #阿里云账户
  regionId: cn-hangzhou
  accessKeyId: 111
  accesKeySecret: 111
req:  #短信验证码模板
  signName: TreeHole树洞
  templateCode: SMS_209821417
